# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'bookinfoadd.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(684, 516)
        self.bookname_la = QtWidgets.QLabel(Form)
        self.bookname_la.setGeometry(QtCore.QRect(80, 50, 72, 15))
        self.bookname_la.setObjectName("bookname_la")
        self.bookdesc_la = QtWidgets.QLabel(Form)
        self.bookdesc_la.setGeometry(QtCore.QRect(80, 240, 71, 16))
        self.bookdesc_la.setObjectName("bookdesc_la")
        self.booktype_la = QtWidgets.QLabel(Form)
        self.booktype_la.setGeometry(QtCore.QRect(80, 170, 72, 15))
        self.booktype_la.setObjectName("booktype_la")
        self.bookprice_la = QtWidgets.QLabel(Form)
        self.bookprice_la.setGeometry(QtCore.QRect(380, 110, 72, 15))
        self.bookprice_la.setObjectName("bookprice_la")
        self.authorgender_la = QtWidgets.QLabel(Form)
        self.authorgender_la.setGeometry(QtCore.QRect(80, 110, 72, 15))
        self.authorgender_la.setObjectName("authorgender_la")
        self.bookauthor_la = QtWidgets.QLabel(Form)
        self.bookauthor_la.setGeometry(QtCore.QRect(380, 50, 72, 15))
        self.bookauthor_la.setObjectName("bookauthor_la")
        self.bookname_le = QtWidgets.QLineEdit(Form)
        self.bookname_le.setGeometry(QtCore.QRect(170, 50, 113, 21))
        self.bookname_le.setObjectName("bookname_le")
        self.bookauthor_le = QtWidgets.QLineEdit(Form)
        self.bookauthor_le.setGeometry(QtCore.QRect(470, 50, 113, 21))
        self.bookauthor_le.setObjectName("bookauthor_le")
        self.bookprice_le = QtWidgets.QLineEdit(Form)
        self.bookprice_le.setGeometry(QtCore.QRect(470, 110, 113, 21))
        self.bookprice_le.setObjectName("bookprice_le")
        self.man_rbtn = QtWidgets.QRadioButton(Form)
        self.man_rbtn.setGeometry(QtCore.QRect(170, 110, 41, 19))
        self.man_rbtn.setMouseTracking(True)
        self.man_rbtn.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.man_rbtn.setChecked(True)
        self.man_rbtn.setObjectName("man_rbtn")
        self.female_rbtn = QtWidgets.QRadioButton(Form)
        self.female_rbtn.setGeometry(QtCore.QRect(240, 110, 41, 19))
        self.female_rbtn.setObjectName("female_rbtn")
        self.booktype_cb = QtWidgets.QComboBox(Form)
        self.booktype_cb.setGeometry(QtCore.QRect(170, 170, 111, 22))
        self.booktype_cb.setObjectName("booktype_cb")
        self.add_btn = QtWidgets.QPushButton(Form)
        self.add_btn.setGeometry(QtCore.QRect(80, 450, 93, 28))
        self.add_btn.setObjectName("add_btn")
        self.reset_btn = QtWidgets.QPushButton(Form)
        self.reset_btn.setGeometry(QtCore.QRect(380, 450, 93, 28))
        self.reset_btn.setObjectName("reset_btn")
        self.bookdesc_pte = QtWidgets.QPlainTextEdit(Form)
        self.bookdesc_pte.setGeometry(QtCore.QRect(170, 240, 421, 201))
        self.bookdesc_pte.setObjectName("bookdesc_pte")

        self.retranslateUi(Form)
        self.add_btn.clicked.connect(Form.add_book) # type: ignore
        self.reset_btn.clicked.connect(Form.reset) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.bookname_la.setText(_translate("Form", "图书名称："))
        self.bookdesc_la.setText(_translate("Form", "图书表述："))
        self.booktype_la.setText(_translate("Form", "图书类别："))
        self.bookprice_la.setText(_translate("Form", "图书价格："))
        self.authorgender_la.setText(_translate("Form", "作者性别："))
        self.bookauthor_la.setText(_translate("Form", "图书作者："))
        self.man_rbtn.setText(_translate("Form", "男"))
        self.female_rbtn.setText(_translate("Form", "女"))
        self.add_btn.setText(_translate("Form", "添加"))
        self.reset_btn.setText(_translate("Form", "重置"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
