# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'editbooktype.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(655, 739)
        self.groupBox = QtWidgets.QGroupBox(Form)
        self.groupBox.setGeometry(QtCore.QRect(50, 30, 551, 101))
        self.groupBox.setObjectName("groupBox")
        self.booktypename_la = QtWidgets.QLabel(self.groupBox)
        self.booktypename_la.setGeometry(QtCore.QRect(20, 40, 101, 16))
        self.booktypename_la.setObjectName("booktypename_la")
        self.booktypename_le = QtWidgets.QLineEdit(self.groupBox)
        self.booktypename_le.setGeometry(QtCore.QRect(130, 40, 191, 20))
        self.booktypename_le.setObjectName("booktypename_le")
        self.search_btn = QtWidgets.QPushButton(self.groupBox)
        self.search_btn.setGeometry(QtCore.QRect(390, 40, 93, 28))
        self.search_btn.setObjectName("search_btn")
        self.booktype_table = QtWidgets.QTableWidget(Form)
        self.booktype_table.setGeometry(QtCore.QRect(50, 140, 551, 291))
        self.booktype_table.setStyleSheet("")
        self.booktype_table.setObjectName("booktype_table")
        self.booktype_table.setColumnCount(0)
        self.booktype_table.setRowCount(0)
        self.groupBox_2 = QtWidgets.QGroupBox(Form)
        self.groupBox_2.setGeometry(QtCore.QRect(50, 440, 551, 281))
        self.groupBox_2.setObjectName("groupBox_2")
        self.id_la = QtWidgets.QLabel(self.groupBox_2)
        self.id_la.setGeometry(QtCore.QRect(30, 30, 41, 16))
        self.id_la.setObjectName("id_la")
        self.id_le = QtWidgets.QLineEdit(self.groupBox_2)
        self.id_le.setGeometry(QtCore.QRect(80, 30, 81, 20))
        self.id_le.setStyleSheet("")
        self.id_le.setReadOnly(True)
        self.id_le.setObjectName("id_le")
        self.booktypename2_la = QtWidgets.QLabel(self.groupBox_2)
        self.booktypename2_la.setGeometry(QtCore.QRect(260, 30, 101, 16))
        self.booktypename2_la.setObjectName("booktypename2_la")
        self.booktypename2_le = QtWidgets.QLineEdit(self.groupBox_2)
        self.booktypename2_le.setGeometry(QtCore.QRect(370, 30, 113, 20))
        self.booktypename2_le.setObjectName("booktypename2_le")
        self.desc_la = QtWidgets.QLabel(self.groupBox_2)
        self.desc_la.setGeometry(QtCore.QRect(20, 80, 41, 16))
        self.desc_la.setObjectName("desc_la")
        self.desc_plt = QtWidgets.QPlainTextEdit(self.groupBox_2)
        self.desc_plt.setGeometry(QtCore.QRect(80, 80, 401, 111))
        self.desc_plt.setObjectName("desc_plt")
        self.modify_btn = QtWidgets.QPushButton(self.groupBox_2)
        self.modify_btn.setGeometry(QtCore.QRect(80, 230, 93, 28))
        self.modify_btn.setObjectName("modify_btn")
        self.del_btn = QtWidgets.QPushButton(self.groupBox_2)
        self.del_btn.setGeometry(QtCore.QRect(390, 230, 93, 28))
        self.del_btn.setObjectName("del_btn")

        self.retranslateUi(Form)
        self.search_btn.clicked.connect(Form.search) # type: ignore
        self.booktype_table.clicked['QModelIndex'].connect(Form.init_form) # type: ignore
        self.modify_btn.clicked.connect(Form.update_form) # type: ignore
        self.del_btn.clicked.connect(Form.delete_row) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.groupBox.setTitle(_translate("Form", "查询操作"))
        self.booktypename_la.setText(_translate("Form", "图书类别名称"))
        self.search_btn.setText(_translate("Form", "搜索"))
        self.groupBox_2.setTitle(_translate("Form", "表单操作"))
        self.id_la.setText(_translate("Form", "编号"))
        self.booktypename2_la.setText(_translate("Form", "图书类别名称"))
        self.desc_la.setText(_translate("Form", "描述"))
        self.modify_btn.setText(_translate("Form", "修改"))
        self.del_btn.setText(_translate("Form", "删除"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
