# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(575, 422)
        self.login_btn = QtWidgets.QPushButton(Form)
        self.login_btn.setGeometry(QtCore.QRect(150, 340, 93, 28))
        self.login_btn.setObjectName("login_btn")
        self.reset_btn = QtWidgets.QPushButton(Form)
        self.reset_btn.setGeometry(QtCore.QRect(340, 340, 93, 28))
        self.reset_btn.setObjectName("reset_btn")
        self.formLayoutWidget = QtWidgets.QWidget(Form)
        self.formLayoutWidget.setGeometry(QtCore.QRect(150, 160, 281, 171))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(10, 10, 10, 10)
        self.formLayout.setHorizontalSpacing(25)
        self.formLayout.setVerticalSpacing(40)
        self.formLayout.setObjectName("formLayout")
        self.user_name_la = QtWidgets.QLabel(self.formLayoutWidget)
        self.user_name_la.setObjectName("user_name_la")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.user_name_la)
        self.pwd_la = QtWidgets.QLabel(self.formLayoutWidget)
        self.pwd_la.setObjectName("pwd_la")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.pwd_la)
        self.user_name_le = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.user_name_le.setObjectName("user_name_le")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.user_name_le)
        self.pwd_le = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.pwd_le.setEchoMode(QtWidgets.QLineEdit.Password)
        self.pwd_le.setObjectName("pwd_le")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.pwd_le)
        self.title_la = QtWidgets.QLabel(Form)
        self.title_la.setGeometry(QtCore.QRect(230, 80, 201, 41))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(18)
        self.title_la.setFont(font)
        self.title_la.setObjectName("title_la")

        self.retranslateUi(Form)
        self.login_btn.clicked.connect(Form.login) # type: ignore
        self.reset_btn.clicked.connect(Form.reset) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.login_btn.setText(_translate("Form", "登录"))
        self.reset_btn.setText(_translate("Form", "重置"))
        self.user_name_la.setText(_translate("Form", "用户名"))
        self.pwd_la.setText(_translate("Form", "密   码"))
        self.title_la.setText(_translate("Form", "图书馆里系统"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
