# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'modifypwd.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(534, 398)
        self.formLayoutWidget = QtWidgets.QWidget(Form)
        self.formLayoutWidget.setGeometry(QtCore.QRect(80, 50, 371, 251))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(10, 30, 10, 10)
        self.formLayout.setHorizontalSpacing(20)
        self.formLayout.setVerticalSpacing(30)
        self.formLayout.setObjectName("formLayout")
        self.username_la = QtWidgets.QLabel(self.formLayoutWidget)
        self.username_la.setObjectName("username_la")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.username_la)
        self.username_le = QtWidgets.QLabel(self.formLayoutWidget)
        self.username_le.setText("")
        self.username_le.setObjectName("username_le")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.username_le)
        self.oldpwd_la = QtWidgets.QLabel(self.formLayoutWidget)
        self.oldpwd_la.setObjectName("oldpwd_la")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.oldpwd_la)
        self.newpwd_la = QtWidgets.QLabel(self.formLayoutWidget)
        self.newpwd_la.setObjectName("newpwd_la")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.newpwd_la)
        self.confirmpwd_la = QtWidgets.QLabel(self.formLayoutWidget)
        self.confirmpwd_la.setObjectName("confirmpwd_la")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.confirmpwd_la)
        self.oldpwd_le = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.oldpwd_le.setEchoMode(QtWidgets.QLineEdit.Password)
        self.oldpwd_le.setObjectName("oldpwd_le")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.oldpwd_le)
        self.newpwd_le = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.newpwd_le.setEchoMode(QtWidgets.QLineEdit.Password)
        self.newpwd_le.setObjectName("newpwd_le")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.newpwd_le)
        self.confirmpwd_le = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.confirmpwd_le.setEchoMode(QtWidgets.QLineEdit.Password)
        self.confirmpwd_le.setObjectName("confirmpwd_le")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.confirmpwd_le)
        self.commit_btn = QtWidgets.QPushButton(Form)
        self.commit_btn.setGeometry(QtCore.QRect(80, 330, 93, 28))
        self.commit_btn.setObjectName("commit_btn")

        self.retranslateUi(Form)
        self.commit_btn.clicked.connect(Form.submit) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.username_la.setText(_translate("Form", "用户名："))
        self.oldpwd_la.setText(_translate("Form", "旧密码："))
        self.newpwd_la.setText(_translate("Form", "新密码："))
        self.confirmpwd_la.setText(_translate("Form", "确认密码："))
        self.commit_btn.setText(_translate("Form", "提交"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
